# -*- coding: utf-8 -*-
"""Covid-19 Deaths Prediction(India).ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1bzfetDjXJ-NRQatRKmbhaiHTuwpIiQ6z
"""

# Commented out IPython magic to ensure Python compatibility.
import pandas as pd
import numpy as np
import plotly.express as px
# %pip install autots
from autots import AutoTS

# You can get dataset from => https://raw.githubusercontent.com/amankharwal/Website-data/master/COVID19%20data%20for%20overall%20INDIA.csv
data = pd.read_csv("/content/covid19.csv")
data.head()

data.isnull().sum()

"""We don’t need the date column, so let’s drop this column from our dataset:"""

data.drop("Date", axis=1, inplace=True)

data.head(2)

"""Let’s have a look at the daily confirmed cases of Covid-19:"""

fig = px.bar(data, x='Date_YMD', y='Daily Confirmed')
fig.show()

"""Now let’s have a look at the daily deaths of covid-19"""

fig = px.bar(data, x='Date_YMD', y='Daily Deceased')
fig.show()

"""Now let’s visualize the death rate due to Covid-19"""

cases = data["Daily Confirmed"].sum()
deceased = data["Daily Deceased"].sum()

labels = ["Confirmed", "Deceased"]
values = [cases, deceased]

fig = px.pie(data, values=values, 
             names=labels, 
             title='Daily Confirmed Cases vs Daily Deaths', hole=0.5)
fig.show()

model = AutoTS(forecast_length=30, frequency='infer', ensemble='simple')
model = model.fit(data, date_col="Date_YMD", value_col='Daily Deceased', id_col=None)
prediction = model.predict()

forecast = prediction.forecast
forecast